/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by hbm2java", 0)}
 */
<#include "Ejb3TypeDeclaration.ftl"/>
<#if pojo.hasMetaAttribute("json-ignore-annotation")>
@${pojo.importType("org.codehaus.jackson.annotate.JsonIgnoreProperties")}({${pojo.getMetaAsString("json-ignore-annotation","\n")}})
</#if>
<#if pojo.hasMetaAttribute("json-order")>
@${pojo.importType("org.codehaus.jackson.annotate.JsonPropertyOrder")}({${pojo.getMetaAsString("json-order","\n")}})
</#if>
@${pojo.importType("java.lang.SuppressWarnings")}("serial")
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} ${pojo.getExtendsDeclaration()} ${pojo.getImplementsDeclaration()}